### PR TITLE
Check if null before returning value

### LINKED ISSUE #50: Check for null before stringifying objects
Somewhat related to #30, as `null` is an object in JavaScript it gets caught by the object if-statement and then gets stringified which converts it to a string.

screen shot 2018-12-13 at 14 35 53

I think it would be best to check for `null`, and return a string before rendering the cell. Thoughts?

### PR DESCRIPTION
**Pull request by dextermb**
Closes #50

### CODE REVIEW

**Comment by dextermb** [comment]
@DivineOmega Is it not worth getting some other pull requests done before publishing? Like documenting `DynamicAjaxDataTable`?

**Comment by DivineOmega** [comment]
@dextermb Certainly a good idea. :+1:

I'd recommend we bump the version number in this PR, get it merged, and then when we've done sufficient additional breaking PRs, publish.

**Comment by dextermb** [comment]
@DivineOmega Done 👍

**Comment by DivineOmega** [comment]
@dextermb Shall I publish immediately or do you have other issues you intend to work on?

**Comment by dextermb** [comment]
> @dextermb Shall I publish immediately or do you have other issues you intend to work on?

Can push for now, as we are smashing another project at the moment. Will have to come back to the other issues another time.

_Although this change is not required for what we are doing_

**Pull request merged**
