### PR TITLE
Add showLoadingAfterInitialLoad prop

### LINKED ISSUE #35: Do not update the loading prop after the first page
After loading the first page through the AJAX Data Table, it should not update the loading prop.
I will do this at some point.

### PR DESCRIPTION
**Pull request by dextermb**
Closes #35

### CODE REVIEW

**Comment by DivineOmega** [comment]
I like the functionality and implementation. :+1: 

I'm trying to think if there is a simpler prop name we can use. What are your thought on the following?

* `onlyShowLoadingOnce`
* `onlyLoadOnce`
* `initialLoadingOnly`
* `showLoadingOnce`
* `onlyDisplayLoadingOnce`

I think `onlyShowLoadingOnce` is perhaps the clearest.

**Comment by dextermb** [comment]
> I like the functionality and implementation. 👍
> 
> I'm trying to think if there is a simpler prop name we can use. What are your thought on the following?
> 
> * `onlyShowLoadingOnce`
> * `onlyLoadOnce`
> * `initialLoadingOnly`
> * `showLoadingOnce`
> * `onlyDisplayLoadingOnce`
> 
> I think `onlyShowLoadingOnce` is perhaps the clearest.

I think this one `onlyLoadOnce` is misleading, but `onlyShowLoadingOnce` could be updated.

**Comment by DivineOmega** [comment]
I agree. Let's go with `onlyShowLoadingOnce`. You'll probably need to reverse the logic for it to make sense, as this prop name is linguistically opposite to the current one.

Default it to `false` to maintain the current behaviour.

Then feel free to bump the minor version number.

**Comment by DivineOmega** [comment]
I would say document it, but of course this is a prop of the currently undocumented ajax component.

**Comment by dextermb** [comment]
🚧 👷 I believe this is finally how you want it

**Comment by dextermb** [comment]
@DivineOmega I have resolved merge conflicts and updated the version number to `6.1.0`. This should be safe to approve and merge in again.

**Pull request closed without merging**
