### PR TITLE
Modified the default callback parameters for buttons

### PR DESCRIPTION
**Pull request by reegoram**
The event parameter is required as first param. This intends to solve #82

### CODE REVIEW

**Comment by dextermb** [comment]
Thanks for your contribution 🎉

Would you be able to rebuild dist and bump the package version too?

```
npm run build
```

```
7.4.1 -> 7.4.2
```

**Comment by reegoram** [comment]
Sure, Should I commit the generated files @ static?

**Comment by DivineOmega** [comment]
Thanks for the contribution @reegoram. We'll probably get this merged and released tomorrow. :+1:

**Comment by dextermb** [comment]
👍 Released as of [`7.4.2`](https://www.npmjs.com/package/@langleyfoxall/react-dynamic-data-table/v/7.4.2).

**Pull request merged**
