### PR TITLE
Add disabledCheckboxes prop

### PR DESCRIPTION
**Pull request by JacobBrassington**
This PR implements the functionality to pass an array of identifiers into the `disabledCheckboxes` prop which then allows for individual checkbox disabling per row.

Example:
```jsx
<DynamicDataTable
    rows={this.state.users}
    renderCheckboxes
    disabledCheckboxes={[1]}
/>
```

### CODE REVIEW

**Comment by robmilward** [comment]
I'd get a thumbs up from @DivineOmega too :)

**Comment by DivineOmega** [comment]
Sorry I didn't get on to reviewing this yesterday.

I think I'd prefer this implementation not reference `row.id` directly. Although we mostly use `id` fields in our databases, and it's common practice, there are plenty of examples of other names being used at the primary identifier of a table.

Perhaps it would be worth making this more flexible at the same time. A syntax such as the following would allow developers to disable the checkbox based on an callable which received the entire row of data.

```jsx
disableCheckbox={(row) => {
    return (row.name === 'test');
}}
```

**Comment by dextermb** [comment]
> I think I'd prefer this implementation not reference row.id directly. Although we mostly use id fields in our databases, and it's common practice, there are plenty of examples of other names being used at the primary identifier of a table.

I had discussed this when thinking of the best solution. As a quick win (due to this being blocking on a project) we went with the simplest option.

Eventually we should definitely move away from relying on IDs, but that'd come under a separate PR and be done all in one go IMO.

**Comment by DivineOmega** [comment]
@dextermb Are there still other locations that rely on `row.id`. I thought all (or at all almost all) had been removed now.

**Comment by dextermb** [comment]
> @dextermb Are there still other locations that rely on `row.id`? I thought all (or at all almost all) had been removed now.

Such as the `key` for `DataRow`.

**Comment by dextermb** [comment]
@DivineOmega [I've create a branch](https://github.com/dextermb/react-dynamic-data-table/tree/feature/custom-identifier-custom-disable-logic) that implements a custom `disableCheckboxes` callable prop and a `rowIdentifier` prop. Have a read on the recent commits before I open a PR, I believe you'll be able to comment on the commits too.

**Pull request merged**
